name: prompt-iqa
channels:
  - defaults
  - conda-forge
  - nvidia

dependencies:
  - python=3.10
  - pip
  - cuda-toolkit=12.1
  - cudnn=8.9
  - libglib=2.80.3
  - ninja
  - pip:
      - -r requirements.txt
